<?php

namespace app\admin\controller;

use app\admin\middleware\Check;
use app\common\controller\AdminBase;
use app\index\model\Classify;
use app\index\model\Joggle;
use app\Request;

//文章列表
class ArticleList   extends  AdminBase
{
    protected $middleware = [
        Check::class => [], //控制器中间件定义
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this -> JoggleModel = new Joggle();
        $this -> ClassifyModel  = new Classify();
    }

    public function index(Request $request){
        if($request->isGet()){

            return $this->fetch('');
        }


    }
//    表格数据完成
//    分页完成
    public function table_data(Request $request){
        $req_data = $request->get();

        $reqult = [
            'code'  =>  0,
            'msg'   =>  '成功',
            'count' =>  Joggle::count(),
            'data'  =>  $this->JoggleModel->Fpage($req_data['limit'],$req_data['page'])

        ];

        return json($reqult);
    }

    public function del(Request $request){
        if($request->isPost()){
            $id = $request->post('id');
            $this->JoggleModel->Fdel($id);
            return json([
                'code'=>200,
                'msg'   =>"删除成功"
            ]);
        }
    }

    public function del_sel(Request $request){
        if($request->isPost()){
            $ids = $request->post('ids');

            Joggle::destroy($ids);
            return json([
                'code'=>200,
                'msg'   =>"删除成功",
            ]);

        }
    }

    public function stop(Request $request){
        if($request->isPost()){
            $data = $request->post();
//            $JoggleModel = new Joggle;
            $this->JoggleModel->Fstop($data['id'],$data['status']);
            return json([
                'code'    =>  200,
                'msg'       =>  '成功'
            ]);
        }
        return $this->fetch('');
    }

    public function add_edit(Request $request){
        if($request->isGet()){
            $id = $request->param('id');
            $reqult = [];
            $reqult['id'] =   $id;
            $reqult['one_sel']  =  Classify::scope('status')->where("rank",null)->select();
            if($id != 0){
                $reqult['data'] =  Joggle::where("id",$id) ->find();
            }
            return $this->fetch('',$reqult);
        }elseif ($request->isPost()){
            $data = $request->post();
            if($data['id'] == 0){
                if($data['select_level2']){
                    $data['classify_id'] = $data['select_level2'];
                }else{
                    $data['classify_id'] = $data['select_level1'];
                }
                $this->JoggleModel->Fadd($data);
            }else{
                $this->JoggleModel->Fedit($data['id'],$data);
            }

            return json([
                'status'=>200,
                'msg'   =>"成功"
            ]);
        }

    }

    public function two_select(Request $request){
        if($request->isPost()){
            $id = $request->post('id');
            $two = $this->ClassifyModel->FGetOnwRand($id);
            return json([
                'code'  => 200,
                'data'   =>  $two
            ]);
        }
    }
}