<?php

namespace app\admin\controller;

use app\admin\middleware\Check;
use app\common\controller\AdminBase;
use app\index\model\Classify;
use app\Request;

//    文章类型列表
class ArticleTypeList  extends  AdminBase
{

    protected $middleware = [
        Check::class => [], //控制器中间件定义
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->ClassifyModel = new Classify();
    }

    public function index(){

        return $this->fetch('');
    }

    public function table_data(Request $request){
        $data = $request->get();
        $reqult = [
            'code'  =>  0,
            'msg'   =>  '成功',
            'count' =>  Classify::count(),
            'data'  =>  $this->ClassifyModel->Fpage($data['limit'],$data['page'])
        ];

        return json($reqult);
    }

    public function add_edit(Request $request){
        if($request->isGet()){
            $class_id = $request->param('id');
            $reqult = [];
            $reqult['class_id'] =   $class_id;
            $reqult["type"] = Classify::scope('status')->where("rank",null)->select();
//            添加分类
            if($class_id != 0){
                $reqult["con"] = Classify::scope('status')->where("id",$class_id)->find();
            }
            return $this->fetch('',$reqult);
        }elseif ($request->isPost()){
            $data = $request->post();
            if($data['id'] == 0){

                $this->ClassifyModel->Fadd($data);

            }else{
                $this->ClassifyModel->Fedit($data['id'],$data);
            }

            return json([
                'status'=>200,
                'msg'   =>"成功"
                ]);
        }

    }

    public function stop(Request $request){

        if($request->isPost()){
            $data = $request->post();
            $this->ClassifyModel->Fstop($data['id'],$data['status']);
            return json([
                'code'    =>  200,
                'msg'       =>  '成功'
            ]);
        }
        return $this->fetch('');
    }

    public function del(Request $request){
        if($request->isPost()){
            $id = $request->post('id');
            $this->ClassifyModel->Fdel($id);
            return json([
                'code'=>200,
                'msg'   =>"删除成功"
            ]);
        }
    }

    public function del_sel(Request $request){
        if($request->isPost()){
            $ids = $request->post('ids');

            Classify::destroy($ids);
            return json([
                'code'=>200,
                'msg'   =>"删除成功",
            ]);

        }

    }
}